= Overview

:toc:

[cloud-intro]

== Module: Cloud Introduction (theory-block I)

* What is Cloud Computing? Encounters in everyday life and history
* Characteristic, advantages & challenges
* Terminology - public, private, hybrid, dedicated
* Abstraction layers - IaaS, PaaS, FaaS, SaaS
* Overview - Hypervisors, virtual machines, containers and orchestration
* Overview - Global cloud service providers (CSPs), technologies and corresponding offerings

=== Objectives and exercises
_The student is able to describe cloud computing in own words and list examples for offerings, topologies and technologies. Includes ability to differentiate between different abstraction layers and knowledge how those layers and according technologies interact with each other. No exercises in this module_

=== Links

 * https://landscape.cncf.io/
 * https://www.cncf.io/wp-content/uploads/2020/11/CNCF_Survey_Report_2020.pdf
 * https://csrc.nist.gov/publications/detail/sp/800-145/final

=== Review questions

* What modern, current technologies relate to the topic of distributed computing. List 3 and explain why.
* Describe 3 abstraction layers of cloud (incl. abbreviation) and list a technology example for each.
* What characteristics and features can I expect as a service consumer from the various layers.
* List pros and cons for cloud (generic) - X examples each

=== Open Questions

* Differences between FaaS and API
* 

