apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hse-deploy
  name: hse-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hse-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hse-deploy
    spec:
      containers:
      - image: maeddes/kubernetes-demo:v2
        name: kubernetes-demo
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "postgres"
        - name: spring.datasource.url 
          value: "jdbc:postgresql://10.0.208.234:5432/ShoppingList"
        readinessProbe:
          httpGet:
            path: /demo
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources: {}
status: {}
