apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hse-deploy
  name: hse-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hse-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
