apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hse-demo
  name: hse-demo
spec:
  containers:
  - env:
    - name: SPRING_PROFILES_ACTIVE
      value: h2
    image: maeddes/kubernetes-demo:v0.1
    name: hse-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
