apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
  name: my-dep
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-dep
  type: LoadBalancer
status:
  loadBalancer: {}
