apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shoppinglistdb
  name: shoppinglistdb
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: shoppinglistdb
status:
  loadBalancer: {}
